#!/usr/bin/env python3

import subprocess
import sys

sys.path.append(".")
from fuzz import Fuzzer

apf = sys.argv[1]


def apf_test(in_, out, *args):
    args = list(map(lambda x: str(x), args))
    result = subprocess.run(
        [apf, in_, *args], stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    try:
        res = result.stdout.decode("utf-8")
    except UnicodeDecodeError:
        print(f"test failed: '{in_}'")
        print(f"garbled results: {result.stdout}")
        sys.exit(1)

    if out is None:
        if result.returncode != 0:
            print(f"test failed: '{in_}'")
            print(result.stderr.decode("utf-8"))
            sys.exit(1)
    elif res != out:
        print(f"test failed: '{in_}'")
        if result.stderr:
            print(result.stderr.decode("utf-8"))
        print(f"got:      '{res}'")
        print(f"expected: '{out}'")

        sys.exit(1)


apf_test("test", "test")
apf_test("test {}", "test string", "string")
apf_test("{:.3}", "1.500", 1.5)
apf_test("{}", "80", 80)
apf_test("{=:#>10}", "##########")
apf_test("{?a:b}", "a", 1)
apf_test("{?a:b}", "b", 0)
apf_test("a{=b:>9}", "a        b")
apf_test("片{}", "片仮名", "仮名")
apf_test("{?{={?a:b{}}}}d", "bcd", 1, 0, "c")
apf_test("片{:>5}", "片 仮名", "仮名")
apf_test("{=片{:>5}:>8}", " 片 仮名", "仮名")

fuzzer = Fuzzer()
amnt = 1000
for x in range(amnt):
    if x % 1000 == 0:
        print("\r%3d%%, %d / %d" % (x * 100.0 / amnt, x, amnt))
    string = fuzzer.gen()
    apf_test(string, None, *fuzzer.args())
