#!/usr/bin/env python3

import sys

from apf_grammar import cfg
from fuzzer import Fuzzer, str_tree, print_tree
from examples import ExampleTesterCExt, Example, examples

tester = ExampleTesterCExt(sys.argv[1])

examples.test(tester)

fuzzer = Fuzzer(cfg)

for x in range(3000):
    tree = fuzzer.gen(cfactor=0.8)

    if not tester.test(Example(str_tree(tree), None, fuzzer.args())):
        print_tree(tree)
        sys.exit(1)
