image: alpine/edge
packages:
  #- ruby
  #- ruby-dev
  - meson
  - ninja
sources:
  - https://github.com/annacrombie/altprintf
tasks:
  - setup: |
      #sudo gem install bundler --no-document --quiet
      #cd altprintf
      #bundle install
      #cd gem
      #bundle install
  - build: |
      cd altprintf
      meson build
      ninja -C build
