image: alpine/edge
shell: true
packages:
  - ruby
  - ruby-dev
sources:
  - https://github.com/annacrombie/altprintf
tasks:
  - setup: |
      sudo gem install bundler -N
      cd altprintf
      bundle install
      cd gem
      bundle install
  - build: |
      cd altprintf
      CFLAGS="-fPIC" make
      make gem
  - test: |
      cd altprintf
      rspec
