image: alpine/edge
packages:
  - meson
  - ninja
  - ruby
  - ruby-dev
sources:
  - https://github.com/annacrombie/altprintf
tasks:
  - setup: |
      sudo gem install bundler --no-document --quiet
      cd altprintf
      meson build
      cd gem
      bundle install
  - build: |
      cd altprintf
      ninja -C build
  - build_gem: |
      cd altprintf/gem
      bundle exec rake compile
  - test: |
      cd altprintf/gem
      FUZZ_COUNT=2000 QUIET_RUNNER=1 FAIL_FAST=1 bundle exec rspec
