image: alpine/edge
packages:
  - meson
  - samurai
  - scdoc
sources:
  - https://github.com/annacrombie/altprintf
tasks:
  - setup: |
      cd altprintf
      meson build
  - build: |
      cd altprintf
      samu -C build
  - test: |
      cd altprintf
      samu -C build test
