require 'rake/extensiontask'
require 'securerandom'
require 'fileutils'

SRC_DIR = File.join(__dir__, '../subprojects/libaltprintf/src/')
INC_DIR = File.join(__dir__, '../subprojects/libaltprintf/include/altprintf')

Rake::ExtensionTask.new('altprintf') do |ext|
  ext.lib_dir = 'lib/altprintf'
  ext.config_script = 'extconf_dev.rb'
end

task :clean do
  sh "rm -rf tmp"
  sh "rm -f lib/altprintf/altprintf.so"
end

namespace :gem do
  desc 'copy necessary c files from ../src and build the resulting gem'
  task :build do
    tmp_dir = "/tmp/altprintf_#{SecureRandom.hex(8)}"
    puts "cloning to #{tmp_dir}"
    FileUtils.mkdir(tmp_dir)

    Dir[
      'readme.md',
      'altprintf.gemspec',
      'lib/**/*.rb',
      'ext/**/*.{c,h}',
      'ext/altprintf/extconf.rb',
      'ext/altprintf/extconf_helper.rb'
    ].each do |f|
      next if File.directory?(f)

      dir = File.join(tmp_dir, File.dirname(f))
      FileUtils.mkdir_p(dir)
      FileUtils.cp(f, File.join(dir, File.basename(f)))
    end

    ext_dir = File.join(tmp_dir, 'ext/altprintf/')
    FileUtils.cp_r(Dir["#{SRC_DIR}/*.c"].flatten, ext_dir)
    FileUtils.cp_r(INC_DIR, ext_dir)

    sh "cd '#{tmp_dir}' && gem build altprintf.gemspec"

    FileUtils.cp(Dir[File.join(tmp_dir, '*.gem')], File.join(__dir__, 'pkg'), verbose: true)
    FileUtils.rm_rf(tmp_dir)
  end

  desc 'pushes the latest gem'
  task :publish do
    load File.join(__dir__, 'altprintf.gemspec')
    pkg = "pkg/#{Altprintf::SPEC.name}-#{Altprintf::SPEC.version}.gem"

    sh "bundle exec rake gem:build" unless File.exist?(pkg)
    sh "gem push #{pkg}"
  end
end
